module.exports = [
  { id: 2, name: '02 – Ambedkar Nagar', nameEn: '02 – Ambedkar Nagar', zone: 'Z1 – City', councillor: 'Councillor 2' },
  { id: 4, name: '04 – Ishapur Yamunapar', nameEn: '04 – Ishapur Yamunapar', zone: 'Z1 – City', councillor: 'Councillor 4' },
  { id: 5, name: '05 – Bharatpur Gate', nameEn: '05 – Bharatpur Gate', zone: 'Z1 – City', councillor: 'Councillor 5' },
  { id: 7, name: '07 – Lohvan', nameEn: '07 – Lohvan', zone: 'Z1 – City', councillor: 'Councillor 7' },
  { id: 14, name: '14 – Lakshmi Nagar Yamunapar', nameEn: '14 – Lakshmi Nagar Yamunapar', zone: 'Z1 – City', councillor: 'Councillor 14' },
  { id: 19, name: '19 – Ramnagar Yamunapar', nameEn: '19 – Ramnagar Yamunapar', zone: 'Z1 – City', councillor: 'Councillor 19' },
  { id: 22, name: '22 – Badhri Nagar', nameEn: '22 – Badhri Nagar', zone: 'Z1 – City', councillor: 'Councillor 22' },
  { id: 23, name: '23 – Aheer Pada', nameEn: '23 – Aheer Pada', zone: 'Z1 – City', councillor: 'Councillor 23' },
  { id: 26, name: '26 – Naya Nagla', nameEn: '26 – Naya Nagla', zone: 'Z1 – City', councillor: 'Councillor 26' },
  { id: 35, name: '35 – Bankhandi', nameEn: '35 – Bankhandi', zone: 'Z1 – City', councillor: 'Councillor 35' },
  { id: 40, name: '40 – Rajkumar', nameEn: '40 – Rajkumar', zone: 'Z1 – City', councillor: 'Councillor 40' },
  { id: 42, name: '42 – Manoharpur', nameEn: '42 – Manoharpur', zone: 'Z1 – City', councillor: 'Councillor 42' },
  { id: 49, name: '49 – Daimpiriyal Nagar', nameEn: '49 – Daimpiriyal Nagar', zone: 'Z1 – City', councillor: 'Councillor 49' },
  { id: 53, name: '53 – Krishna Puri', nameEn: '53 – Krishna Puri', zone: 'Z1 – City', councillor: 'Councillor 53' },
  { id: 61, name: '61 – Chaubia Para', nameEn: '61 – Chaubia Para', zone: 'Z1 – City', councillor: 'Councillor 61' },
  { id: 63, name: '63 – Maliyaan Sadar', nameEn: '63 – Maliyaan Sadar', zone: 'Z1 – City', councillor: 'Councillor 63' },
  { id: 64, name: '64 – Ghati Bahalray', nameEn: '64 – Ghati Bahalray', zone: 'Z1 – City', councillor: 'Councillor 64' },
  { id: 65, name: '65 – Holi Gali', nameEn: '65 – Holi Gali', zone: 'Z1 – City', councillor: 'Councillor 65' },
  { id: 68, name: '68 – Shanti Nagar', nameEn: '68 – Shanti Nagar', zone: 'Z1 – City', councillor: 'Councillor 68' },
  { id: 70, name: '70 – Biharipur', nameEn: '70 – Biharipur', zone: 'Z1 – City', councillor: 'Councillor 70' },
  { id: 3, name: '03 – Girdharpur', nameEn: '03 – Girdharpur', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 3' },
  { id: 12, name: '12 – Radhe Shyam Colony', nameEn: '12 – Radhe Shyam Colony', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 12' },
  { id: 16, name: '16 – Bakalpur', nameEn: '16 – Bakalpur', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 16' },
  { id: 17, name: '17 – Bairaagpura', nameEn: '17 – Bairaagpura', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 17' },
  { id: 20, name: '20 – Krishna Nagar First', nameEn: '20 – Krishna Nagar First', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 20' },
  { id: 24, name: '24 – Sarai Azamabad', nameEn: '24 – Sarai Azamabad', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 24' },
  { id: 30, name: '30 – Krishna Nagar Second', nameEn: '30 – Krishna Nagar Second', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 30' },
  { id: 31, name: '31 – Navneet Nagar', nameEn: '31 – Navneet Nagar', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 31' },
  { id: 36, name: '36 – Jaisingh Pura', nameEn: '36 – Jaisingh Pura', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 36' },
  { id: 37, name: '37 – Baldevpuri', nameEn: '37 – Baldevpuri', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 37' },
  { id: 39, name: '39 – Mahavidhya Colony', nameEn: '39 – Mahavidhya Colony', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 39' },
  { id: 43, name: '43 – Ganeshra', nameEn: '43 – Ganeshra', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 43' },
  { id: 44, name: '44 – Radhika Bihar', nameEn: '44 – Radhika Bihar', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 44' },
  { id: 45, name: '45 – Birla Mandir', nameEn: '45 – Birla Mandir', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 45' },
  { id: 46, name: '46 – Radha Nagar', nameEn: '46 – Radha Nagar', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 46' },
  { id: 47, name: '47 – Dwarkapuri', nameEn: '47 – Dwarkapuri', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 47' },
  { id: 48, name: '48 – Satoha Asangpur', nameEn: '48 – Satoha Asangpur', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 48' },
  { id: 54, name: '54 – Pratap Nagar', nameEn: '54 – Pratap Nagar', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 54' },
  { id: 55, name: '55 – Govind Nagar', nameEn: '55 – Govind Nagar', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 55' },
  { id: 56, name: '56 – Mandi Randas', nameEn: '56 – Mandi Randas', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 56' },
  { id: 58, name: '58 – Gau Ghat', nameEn: '58 – Gau Ghat', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 58' },
  { id: 60, name: '60 – Jagannath Puri', nameEn: '60 – Jagannath Puri', zone: 'Z2 – Bhuteshwar', councillor: 'Councillor 60' },
  { id: 1, name: '01 – Birjapur', nameEn: '01 – Birjapur', zone: 'Z3 – Aurangabad', councillor: 'Councillor 1' },
  { id: 6, name: '06 – Aduki', nameEn: '06 – Aduki', zone: 'Z3 – Aurangabad', councillor: 'Councillor 6' },
  { id: 10, name: '10 – Aurangabad First', nameEn: '10 – Aurangabad First', zone: 'Z3 – Aurangabad', councillor: 'Councillor 10' },
  { id: 11, name: '11 – Tarsi', nameEn: '11 – Tarsi', zone: 'Z3 – Aurangabad', councillor: 'Councillor 11' },
  { id: 15, name: '15 – Maholi First', nameEn: '15 – Maholi First', zone: 'Z3 – Aurangabad', councillor: 'Councillor 15' },
  { id: 27, name: '27 – Baad', nameEn: '27 – Baad', zone: 'Z3 – Aurangabad', councillor: 'Councillor 27' },
  { id: 28, name: '28 – Aurangabad Second', nameEn: '28 – Aurangabad Second', zone: 'Z3 – Aurangabad', councillor: 'Councillor 28' },
  { id: 29, name: '29 – Koyla Alipur', nameEn: '29 – Koyla Alipur', zone: 'Z3 – Aurangabad', councillor: 'Councillor 29' },
  { id: 32, name: '32 – Ranchibagar', nameEn: '32 – Ranchibagar', zone: 'Z3 – Aurangabad', councillor: 'Councillor 32' },
  { id: 33, name: '33 – Palikhera', nameEn: '33 – Palikhera', zone: 'Z3 – Aurangabad', councillor: 'Councillor 33' },
  { id: 38, name: '38 – Civil Lines', nameEn: '38 – Civil Lines', zone: 'Z3 – Aurangabad', councillor: 'Councillor 38' },
  { id: 41, name: '41 – Dhaulipiau', nameEn: '41 – Dhaulipiau', zone: 'Z3 – Aurangabad', councillor: 'Councillor 41' },
  { id: 52, name: '52 – Chandrapuri', nameEn: '52 – Chandrapuri', zone: 'Z3 – Aurangabad', councillor: 'Councillor 52' },
  { id: 57, name: '57 – Balajipuram', nameEn: '57 – Balajipuram', zone: 'Z3 – Aurangabad', councillor: 'Councillor 57' },
  { id: 59, name: '59 – Maholi Second', nameEn: '59 – Maholi Second', zone: 'Z3 – Aurangabad', councillor: 'Councillor 59' },
  { id: 8, name: '08 – Atas', nameEn: '08 – Atas', zone: 'Z4 – Vrindavan', councillor: 'Councillor 8' },
  { id: 9, name: '09 – Gandhi Nagar', nameEn: '09 – Gandhi Nagar', zone: 'Z4 – Vrindavan', councillor: 'Councillor 9' },
  { id: 13, name: '13 – Sunrakh', nameEn: '13 – Sunrakh', zone: 'Z4 – Vrindavan', councillor: 'Councillor 13' },
  { id: 21, name: '21 – Chaitanya Bihar', nameEn: '21 – Chaitanya Bihar', zone: 'Z4 – Vrindavan', councillor: 'Councillor 21' },
  { id: 25, name: '25 – Chharaura', nameEn: '25 – Chharaura', zone: 'Z4 – Vrindavan', councillor: 'Councillor 25' },
  { id: 34, name: '34 – Radhaniwas', nameEn: '34 – Radhaniwas', zone: 'Z4 – Vrindavan', councillor: 'Councillor 34' },
  { id: 50, name: '50 – Patharpura', nameEn: '50 – Patharpura', zone: 'Z4 – Vrindavan', councillor: 'Councillor 50' },
  { id: 51, name: '51 – Gaushala Nagar', nameEn: '51 – Gaushala Nagar', zone: 'Z4 – Vrindavan', councillor: 'Councillor 51' },
  { id: 62, name: '62 – Mathura Darwaza', nameEn: '62 – Mathura Darwaza', zone: 'Z4 – Vrindavan', councillor: 'Councillor 62' },
  { id: 66, name: '66 – Keshighat', nameEn: '66 – Keshighat', zone: 'Z4 – Vrindavan', councillor: 'Councillor 66' },
  { id: 67, name: '67 – Kemar Van', nameEn: '67 – Kemar Van', zone: 'Z4 – Vrindavan', councillor: 'Councillor 67' },
  { id: 69, name: '69 – Ratan Chhatri', nameEn: '69 – Ratan Chhatri', zone: 'Z4 – Vrindavan', councillor: 'Councillor 69' }
];